Add static tombstone method support
scheb/tombstone pull request #18
Opened 2021-05-10 13:44 UTC by lyudmild

2021-05-11 06:59 UTC, scheb commented
Sorry for the delayed builds. I have to push a button for each build, GitHub obviously has introduced that restriction to battle crypo miners.

2021-05-11 12:54 UTC, lyudmild commented
Sorry for all the commits. I haven't worked with php-cs-fixer before.

2021-05-11 18:03 UTC, scheb requested changes
Looks good. Would you please simply that one statement that I commented, then we'd be ready to merge.

2021-05-11 18:03 UTC, scheb commented on src/analyzer/Stock/TombstoneNodeVisitor.php
> +        return false;
This can be a simple `return \in_array($fqn, $this->tombstoneFunctionNames);`

2021-05-11 18:41 UTC, lyudmild commented on src/analyzer/Stock/TombstoneNodeVisitor.php
> +        return false;
I have addressed that. Thank you!

2021-05-12 18:57 UTC, merged

2021-05-12 19:11 UTC, scheb commented
Thank you for your contribution!

Released as v1.4.0